# Generated by Django 5.2.11 on 2026-02-10 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=4096)),
                ('file', models.FileField(upload_to='searches/%Y/%m/%d/')),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.search')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('search', 'source_url'), name='uq_search_source_url')],
            },
        ),
    ]
