# Generated by Django 5.2.11 on 2026-02-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='url',
            field=models.URLField(db_index=True, max_length=2048),
        ),
    ]
